### ISSUE TITLE
a version problem "pip install numpy==1.19.3"

### ISSUE THREAD

**Issue by mwlik** [mmirthula02/AI-Personal-Voice-assistant-using-Python#10]
PS C:\Users\frank\OneDrive\Bureau\projects> py alexa.py
Loading your AI personal assistant - G One
 ** On entry to DGEBAL parameter number  3 had an illegal value       
 ** On entry to DGEHRD  parameter number  2 had an illegal value      
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "C:\Users\frank\OneDrive\Bureau\projects\alexa.py", line 16, in <module>
    engine=pyttsx3.init('sapi5')
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\pyttsx3\__init__.py", line 22, in init  
    eng = Engine(driverName, debug)
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\pyttsx3\drivers\sapi5.py", line 1, in <module>
    import comtypes.client  # Importing comtypes.client will make the gen subpackage
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\__init__.py", line 1176, in <module>
    class IPersist(IUnknown):
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\__init__.py", line 1180, in IPersist
    COMMETHOD([], HRESULT, 'GetClassID',
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\__init__.py", line 1099, in COMMETHOD
    from comtypes.automation import VARIANT
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\automation.py", line 12, in <module>
    from comtypes import npsupport
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\npsupport.py", line 5, in <module>
    import numpy
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\frank\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\frank\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
PS C:\Users\frank\OneDrive\Bureau\projects>

**Comment by mwlik** [comment]
OK! cool I fixed it
