### ISSUE TITLE
ImportError: cannot import name 'COMError' from '_ctypes' (/usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by samibs** [mmirthula02/AI-Personal-Voice-assistant-using-Python#2]
I suppose this is only meant to work on Windows?

I had this issue on Ubuntu 20.04

Loading your AI personal assistant - G One
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/usr/lib/python3.8/weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "firstaitest.py", line 17, in <module>
    engine=pyttsx3.init('sapi5')
  File "/usr/local/lib/python3.8/dist-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/usr/local/lib/python3.8/dist-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/lib/python3.8/dist-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pyttsx3/drivers/sapi5.py", line 1, in <module>
    import comtypes.client  # Importing comtypes.client will make the gen subpackage
  File "/usr/local/lib/python3.8/dist-packages/comtypes/__init__.py", line 23, in <module>
    from _ctypes import COMError
ImportError: cannot import name 'COMError' from '_ctypes' (/usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)

**Comment by sasdallas** [comment]
yeah, just get rid of the sapi5 in engine

**Comment by Amarnath1904** [comment]
Actually you just have to serch how to use Pyttsx3 on  Linux
Because Linux don't use sapi5 it use espeak

I think I can bee wrong because I don't have experience to use Linux 

But I think it should work

```
Sudo apt-get install espeak
```
Or

```
Sudo apt-get update && install espeak
```

**Comment by sai-krishna-ghanta** [comment]
sapi5 - SAPI5 on Windows
nsss - NSSpeechSynthesizer on Mac OS X
espeak - eSpeak on every other platform

So use espeak for your os
